[package]
name = "tldw"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.5.0"
tokio = { version = "1", features = ["full"] }
regex = "1.5"
futures-util = "0.3.28"
chatgpt_rs = { version = "1.1.3", features = ["streams"]}
